#An Ansible role that installs Apache activeMQ
---
- hosts: satcentos
  become_user: root
  become_method: sudo
  gather_facts: true

  pre_tasks:
    - name: Update yum cache.
      yum: name=yum update_cache=yes state=latest
      when: ansible_os_family == 'RedHat'
    
  roles:
    - activemq.eku.install
