# playbook to deploy SSH keys to remote system. this playbook uses https://github.com/KaiserSoft/SSH-Key-Deploy
#  use the following command for a fresh system, one where you don't have your key in authorized_keys yet
#  ansible-playbook -i hosts ssh-deploy.yml --ask-pass
---

- hosts: ansible
  user: root

  roles:
    - ssh-keys
