---
galaxy_info:
  author: " "
  company: AnsibleWorks
  license: license (BSD)
  min_ansible_version: 1.4 
  platforms:
   - name: EL
     versions:
      - 6
      - 7
  categories:
   - database:sql
dependencies: []
  