---

- name: Download and unarchive
  unarchive:
    remote_src: yes
    src: http://archive.apache.org/dist/activemq/{{ activemq_version }}/apache-activemq-{{ activemq_version }}-bin.tar.gz
    dest: "{{ activemq_install_root }}"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    creates: "{{ activemq_install_root }}/apache-activemq-{{ activemq_version }}"

- name: Creating directory for activemq
  file: 
    path: "{{ activemq_install_root }}/activemq"
    state: directory
    recurse: yes
   
- name: Creating symbolic link
  file:
    src: "{{ activemq_install_root }}/apache-activemq-{{ activemq_version }}"
    dest: "{{ activemq_install_root }}/activemq"
    owner: "{{ activemq_user }}"
    group: "{{ activemq_group }}"
    state: link
    force: yes
   
# Transitional removal of old-style init.d symlink
# This task can be removed in the future.
- name: Remove init.d symlink
  file:
    path: /etc/init.d/activemq
    state: absent

- name: Create systemd unit
  template:
    src: activemq.service.j2
    dest: /etc/systemd/system/activemq.service

- name: Reload systemd
  systemd:
    daemon-reload: yes
    enabled: yes
    state: started
    name: activemq

- name: Enable firewalld
  service:
    name: firewalld 
    state: started
    enabled: yes

- name: Set activemq port 61616
  firewalld:
    zone: internal
    port: 61616/tcp
    permanent: true
    state: enabled

- name: Set activemq port 61613
  firewalld:
    zone: internal
    port: 61613/tcp
    permanent: true
    state: enabled

- name: Set activemq port 61614
  firewalld:
    zone: internal
    port: 61614/tcp
    permanent: true
    state: enabled

- name: Set activemq port 8161
  firewalld:
    zone: internal
    port: 8161/tcp
    permanent: true
    state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted

