---
- name: Install Apache
  yum: 
   name: httpd
   state: latest
   update_cache: yes

- name: Install Epel-Release deps
  yum: name={{item}} state=present
  with_items:
  - wget
  - epel-release
 
#- name: Creating directory for httpd.service.d
 # file: 
   # path: /etc/systemd/system/httpd.service.d
    #state: directory
    #recurse: yes

- name: Configure puma-web-service repo
  template:
    src: png.repo.j2
    dest: /etc/yum.repos.d/png.repo
  tags: server

- name: Based on environment,echo "snapshot","test", or "prod"
  shell: echo "test" > /etc/yum/vars/yum_env

- name: Copying puma-web-service conf file
  template:
    src: puma.conf.j2
    dest: /etc/httpd/conf.d/puma.conf

- name: Copying puma-web-service domain.cert file
  template:
    src: domain.cer.j2
    dest: /etc/pki/tls/certs/domain.cer

- name: Copying puma-web-service domain-ca.cert file
  template:
    src: domain-ca.crt.j2
    dest: /etc/pki/tls/certs/domain-ca.crt

- name: Copying puma-web-service domain.key file
  template:
    src: domain.key.j2
    dest: /etc/pki/tls/private/domain.key

- name: Create systemd unit for pumaws
  template:
    src: nopt.conf.j2
    dest: /etc/systemd/system/pumad.service

- name: Reload systemd for puma-ws
  systemd:
    daemon-reload: yes
    enabled: yes
    state: started
    name: httpd

- name: Install puma-ws deps
  yum: name={{item}} state=latest
  with_items:
       #- png.repo
       - wget

- name: Enable firewalld
  service:
    name: firewalld 
    state: started
    enabled: yes

- name: Set https port 443
  firewalld:
    zone: internal
    port: 443/tcp
    permanent: true
    state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: restarted
